package kvb.vkwrapper.persistent

import kvb.vulkan.SampleCountFlags
import kvb.vulkan.PhysicalDeviceLimits

/**
 * Persistent implementation of [VkPhysicalDeviceLimits][PhysicalDeviceLimits].
 */
class PhysicalDeviceLimitsP(
	val maxImageDimension1D: Int,
	val maxImageDimension2D: Int,
	val maxImageDimension3D: Int,
	val maxImageDimensionCube: Int,
	val maxImageArrayLayers: Int,
	val maxTexelBufferElements: Int,
	val maxUniformBufferRange: Int,
	val maxStorageBufferRange: Int,
	val maxPushConstantsSize: Int,
	val maxMemoryAllocationCount: Int,
	val maxSamplerAllocationCount: Int,
	val bufferImageGranularity: Long,
	val sparseAddressSpaceSize: Long,
	val maxBoundDescriptorSets: Int,
	val maxPerStageDescriptorSamplers: Int,
	val maxPerStageDescriptorUniformBuffers: Int,
	val maxPerStageDescriptorStorageBuffers: Int,
	val maxPerStageDescriptorSampledImages: Int,
	val maxPerStageDescriptorStorageImages: Int,
	val maxPerStageDescriptorInputAttachments: Int,
	val maxPerStageResources: Int,
	val maxDescriptorSetSamplers: Int,
	val maxDescriptorSetUniformBuffers: Int,
	val maxDescriptorSetUniformBuffersDynamic: Int,
	val maxDescriptorSetStorageBuffers: Int,
	val maxDescriptorSetStorageBuffersDynamic: Int,
	val maxDescriptorSetSampledImages: Int,
	val maxDescriptorSetStorageImages: Int,
	val maxDescriptorSetInputAttachments: Int,
	val maxVertexInputAttributes: Int,
	val maxVertexInputBindings: Int,
	val maxVertexInputAttributeOffset: Int,
	val maxVertexInputBindingStride: Int,
	val maxVertexOutputComponents: Int,
	val maxTessellationGenerationLevel: Int,
	val maxTessellationPatchSize: Int,
	val maxTessellationControlPerVertexInputComponents: Int,
	val maxTessellationControlPerVertexOutputComponents: Int,
	val maxTessellationControlPerPatchOutputComponents: Int,
	val maxTessellationControlTotalOutputComponents: Int,
	val maxTessellationEvaluationInputComponents: Int,
	val maxTessellationEvaluationOutputComponents: Int,
	val maxGeometryShaderInvocations: Int,
	val maxGeometryInputComponents: Int,
	val maxGeometryOutputComponents: Int,
	val maxGeometryOutputVertices: Int,
	val maxGeometryTotalOutputComponents: Int,
	val maxFragmentInputComponents: Int,
	val maxFragmentOutputAttachments: Int,
	val maxFragmentDualSrcAttachments: Int,
	val maxFragmentCombinedOutputResources: Int,
	val maxComputeSharedMemorySize: Int,
	val maxComputeWorkGroupCount: IntArray,
	val maxComputeWorkGroupInvocations: Int,
	val maxComputeWorkGroupSize: IntArray,
	val subPixelPrecisionBits: Int,
	val subTexelPrecisionBits: Int,
	val mipmapPrecisionBits: Int,
	val maxDrawIndexedIndexValue: Int,
	val maxDrawIndirectCount: Int,
	val maxSamplerLodBias: Float,
	val maxSamplerAnisotropy: Float,
	val maxViewports: Int,
	val maxViewportDimensions: IntArray,
	val viewportBoundsRange: FloatArray,
	val viewportSubPixelBits: Int,
	val minMemoryMapAlignment: Long,
	val minTexelBufferOffsetAlignment: Long,
	val minUniformBufferOffsetAlignment: Long,
	val minStorageBufferOffsetAlignment: Long,
	val minTexelOffset: Int,
	val maxTexelOffset: Int,
	val minTexelGatherOffset: Int,
	val maxTexelGatherOffset: Int,
	val minInterpolationOffset: Float,
	val maxInterpolationOffset: Float,
	val subPixelInterpolationOffsetBits: Int,
	val maxFramebufferWidth: Int,
	val maxFramebufferHeight: Int,
	val maxFramebufferLayers: Int,
	val framebufferColorSampleCounts: SampleCountFlags,
	val framebufferDepthSampleCounts: SampleCountFlags,
	val framebufferStencilSampleCounts: SampleCountFlags,
	val framebufferNoAttachmentsSampleCounts: SampleCountFlags,
	val maxColorAttachments: Int,
	val sampledImageColorSampleCounts: SampleCountFlags,
	val sampledImageIntegerSampleCounts: SampleCountFlags,
	val sampledImageDepthSampleCounts: SampleCountFlags,
	val sampledImageStencilSampleCounts: SampleCountFlags,
	val storageImageSampleCounts: SampleCountFlags,
	val maxSampleMaskWords: Int,
	val timestampComputeAndGraphics: Int,
	val timestampPeriod: Float,
	val maxClipDistances: Int,
	val maxCullDistances: Int,
	val maxCombinedClipAndCullDistances: Int,
	val discreteQueuePriorities: Int,
	val pointSizeRange: FloatArray,
	val lineWidthRange: FloatArray,
	val pointSizeGranularity: Float,
	val lineWidthGranularity: Float,
	val strictLines: Int,
	val standardSampleLocations: Int,
	val optimalBufferCopyOffsetAlignment: Long,
	val optimalBufferCopyRowPitchAlignment: Long,
	val nonCoherentAtomSize: Long,
) {


	constructor(struct: PhysicalDeviceLimits) : this(
		struct.maxImageDimension1D,
		struct.maxImageDimension2D,
		struct.maxImageDimension3D,
		struct.maxImageDimensionCube,
		struct.maxImageArrayLayers,
		struct.maxTexelBufferElements,
		struct.maxUniformBufferRange,
		struct.maxStorageBufferRange,
		struct.maxPushConstantsSize,
		struct.maxMemoryAllocationCount,
		struct.maxSamplerAllocationCount,
		struct.bufferImageGranularity,
		struct.sparseAddressSpaceSize,
		struct.maxBoundDescriptorSets,
		struct.maxPerStageDescriptorSamplers,
		struct.maxPerStageDescriptorUniformBuffers,
		struct.maxPerStageDescriptorStorageBuffers,
		struct.maxPerStageDescriptorSampledImages,
		struct.maxPerStageDescriptorStorageImages,
		struct.maxPerStageDescriptorInputAttachments,
		struct.maxPerStageResources,
		struct.maxDescriptorSetSamplers,
		struct.maxDescriptorSetUniformBuffers,
		struct.maxDescriptorSetUniformBuffersDynamic,
		struct.maxDescriptorSetStorageBuffers,
		struct.maxDescriptorSetStorageBuffersDynamic,
		struct.maxDescriptorSetSampledImages,
		struct.maxDescriptorSetStorageImages,
		struct.maxDescriptorSetInputAttachments,
		struct.maxVertexInputAttributes,
		struct.maxVertexInputBindings,
		struct.maxVertexInputAttributeOffset,
		struct.maxVertexInputBindingStride,
		struct.maxVertexOutputComponents,
		struct.maxTessellationGenerationLevel,
		struct.maxTessellationPatchSize,
		struct.maxTessellationControlPerVertexInputComponents,
		struct.maxTessellationControlPerVertexOutputComponents,
		struct.maxTessellationControlPerPatchOutputComponents,
		struct.maxTessellationControlTotalOutputComponents,
		struct.maxTessellationEvaluationInputComponents,
		struct.maxTessellationEvaluationOutputComponents,
		struct.maxGeometryShaderInvocations,
		struct.maxGeometryInputComponents,
		struct.maxGeometryOutputComponents,
		struct.maxGeometryOutputVertices,
		struct.maxGeometryTotalOutputComponents,
		struct.maxFragmentInputComponents,
		struct.maxFragmentOutputAttachments,
		struct.maxFragmentDualSrcAttachments,
		struct.maxFragmentCombinedOutputResources,
		struct.maxComputeSharedMemorySize,
		struct.maxComputeWorkGroupCount.asArray,
		struct.maxComputeWorkGroupInvocations,
		struct.maxComputeWorkGroupSize.asArray,
		struct.subPixelPrecisionBits,
		struct.subTexelPrecisionBits,
		struct.mipmapPrecisionBits,
		struct.maxDrawIndexedIndexValue,
		struct.maxDrawIndirectCount,
		struct.maxSamplerLodBias,
		struct.maxSamplerAnisotropy,
		struct.maxViewports,
		struct.maxViewportDimensions.asArray,
		struct.viewportBoundsRange.asArray,
		struct.viewportSubPixelBits,
		struct.minMemoryMapAlignment,
		struct.minTexelBufferOffsetAlignment,
		struct.minUniformBufferOffsetAlignment,
		struct.minStorageBufferOffsetAlignment,
		struct.minTexelOffset,
		struct.maxTexelOffset,
		struct.minTexelGatherOffset,
		struct.maxTexelGatherOffset,
		struct.minInterpolationOffset,
		struct.maxInterpolationOffset,
		struct.subPixelInterpolationOffsetBits,
		struct.maxFramebufferWidth,
		struct.maxFramebufferHeight,
		struct.maxFramebufferLayers,
		struct.framebufferColorSampleCounts,
		struct.framebufferDepthSampleCounts,
		struct.framebufferStencilSampleCounts,
		struct.framebufferNoAttachmentsSampleCounts,
		struct.maxColorAttachments,
		struct.sampledImageColorSampleCounts,
		struct.sampledImageIntegerSampleCounts,
		struct.sampledImageDepthSampleCounts,
		struct.sampledImageStencilSampleCounts,
		struct.storageImageSampleCounts,
		struct.maxSampleMaskWords,
		struct.timestampComputeAndGraphics,
		struct.timestampPeriod,
		struct.maxClipDistances,
		struct.maxCullDistances,
		struct.maxCombinedClipAndCullDistances,
		struct.discreteQueuePriorities,
		struct.pointSizeRange.asArray,
		struct.lineWidthRange.asArray,
		struct.pointSizeGranularity,
		struct.lineWidthGranularity,
		struct.strictLines,
		struct.standardSampleLocations,
		struct.optimalBufferCopyOffsetAlignment,
		struct.optimalBufferCopyRowPitchAlignment,
		struct.nonCoherentAtomSize,
	)


}