// This file has been automatically generated.

package kvb.vulkan

/**
 *     // provided by VK_VERSION_1_0

 *     enum VkDescriptorType {
 *         VK_DESCRIPTOR_TYPE_SAMPLER                     = 0
 *         VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER      = 1
 *         VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE               = 2
 *         VK_DESCRIPTOR_TYPE_STORAGE_IMAGE               = 3
 *         VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER        = 4
 *         VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER        = 5
 *         VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER              = 6
 *         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER              = 7
 *         VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC      = 8
 *         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC      = 9
 *         VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT            = 10
 *         VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT    = 1000138000
 *         VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR  = 1000150000
 *         VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV   = 1000165000
 *         VK_DESCRIPTOR_TYPE_MUTABLE_VALVE               = 1000351000
 *     }
 */
@Suppress("unused")
enum class DescriptorType(val value: Int) {
	
	
	SAMPLER(0),
	
	COMBINED_IMAGE_SAMPLER(1),
	
	SAMPLED_IMAGE(2),
	
	STORAGE_IMAGE(3),
	
	UNIFORM_TEXEL_BUFFER(4),
	
	STORAGE_TEXEL_BUFFER(5),
	
	UNIFORM_BUFFER(6),
	
	STORAGE_BUFFER(7),
	
	UNIFORM_BUFFER_DYNAMIC(8),
	
	STORAGE_BUFFER_DYNAMIC(9),
	
	INPUT_ATTACHMENT(10),
	
	INLINE_UNIFORM_BLOCK(1000138000),
	
	ACCELERATION_STRUCTURE_KHR(1000150000),
	
	ACCELERATION_STRUCTURE_NV(1000165000),
	
	MUTABLE(1000351000);


}