// This file has been automatically generated.

package kvb.vulkan

/**
 *     // provided by VK_NV_fragment_shading_rate_enums

 *     enum VkFragmentShadingRateNV {
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_PIXEL_NV       = 0
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_1X2_PIXELS_NV  = 1
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X1_PIXELS_NV  = 4
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X2_PIXELS_NV  = 5
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_2X4_PIXELS_NV  = 6
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_4X2_PIXELS_NV  = 9
 *         VK_FRAGMENT_SHADING_RATE_1_INVOCATION_PER_4X4_PIXELS_NV  = 10
 *         VK_FRAGMENT_SHADING_RATE_2_INVOCATIONS_PER_PIXEL_NV      = 11
 *         VK_FRAGMENT_SHADING_RATE_4_INVOCATIONS_PER_PIXEL_NV      = 12
 *         VK_FRAGMENT_SHADING_RATE_8_INVOCATIONS_PER_PIXEL_NV      = 13
 *         VK_FRAGMENT_SHADING_RATE_16_INVOCATIONS_PER_PIXEL_NV     = 14
 *         VK_FRAGMENT_SHADING_RATE_NO_INVOCATIONS_NV               = 15
 *     }
 */
@Suppress("unused")
enum class FragmentShadingRate(val value: Int) {
	
	
	_1_INVOCATION_PER_PIXEL(0),
	
	_1_INVOCATION_PER_1X2_PIXELS(1),
	
	_1_INVOCATION_PER_2X1_PIXELS(4),
	
	_1_INVOCATION_PER_2X2_PIXELS(5),
	
	_1_INVOCATION_PER_2X4_PIXELS(6),
	
	_1_INVOCATION_PER_4X2_PIXELS(9),
	
	_1_INVOCATION_PER_4X4_PIXELS(10),
	
	_2_INVOCATIONS_PER_PIXEL(11),
	
	_4_INVOCATIONS_PER_PIXEL(12),
	
	_8_INVOCATIONS_PER_PIXEL(13),
	
	_16_INVOCATIONS_PER_PIXEL(14),
	
	NO_INVOCATIONS(15);


}