// This file has been automatically generated.

package kvb.vulkan

/**
 *     enum VkShadingRatePaletteEntryNV {
 *         VK_SHADING_RATE_PALETTE_ENTRY_NO_INVOCATIONS_NV               = 0
 *         VK_SHADING_RATE_PALETTE_ENTRY_16_INVOCATIONS_PER_PIXEL_NV     = 1
 *         VK_SHADING_RATE_PALETTE_ENTRY_8_INVOCATIONS_PER_PIXEL_NV      = 2
 *         VK_SHADING_RATE_PALETTE_ENTRY_4_INVOCATIONS_PER_PIXEL_NV      = 3
 *         VK_SHADING_RATE_PALETTE_ENTRY_2_INVOCATIONS_PER_PIXEL_NV      = 4
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_PIXEL_NV       = 5
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X1_PIXELS_NV  = 6
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_1X2_PIXELS_NV  = 7
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X2_PIXELS_NV  = 8
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_4X2_PIXELS_NV  = 9
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_2X4_PIXELS_NV  = 10
 *         VK_SHADING_RATE_PALETTE_ENTRY_1_INVOCATION_PER_4X4_PIXELS_NV  = 11
 *     }
 */
@Suppress("unused")
enum class ShadingRatePaletteEntry(val value: Int) {
	
	
	NO_INVOCATIONS(0),
	
	_16_INVOCATIONS_PER_PIXEL(1),
	
	_8_INVOCATIONS_PER_PIXEL(2),
	
	_4_INVOCATIONS_PER_PIXEL(3),
	
	_2_INVOCATIONS_PER_PIXEL(4),
	
	_1_INVOCATION_PER_PIXEL(5),
	
	_1_INVOCATION_PER_2X1_PIXELS(6),
	
	_1_INVOCATION_PER_1X2_PIXELS(7),
	
	_1_INVOCATION_PER_2X2_PIXELS(8),
	
	_1_INVOCATION_PER_4X2_PIXELS(9),
	
	_1_INVOCATION_PER_2X4_PIXELS(10),
	
	_1_INVOCATION_PER_4X4_PIXELS(11);


}